### ISSUE TITLE
add documentation 

### ISSUE THREAD

**Issue by jakob-forstmann** [jakob-forstmann/sentiment-analysis-of-youtube-comments#25]
document the following files:

- [x] random-youtube_comments.py: how to reproduce the results
- [x] amazon dataset: how to reproduce the results 
- [x] update requirement.txt for production mode and for the experiments
- [x]  update README fille 
- [x] document how webserver can be setup or provide a docker for starting the webserver

**Comment by Icon1cc** [comment]
1) random-youtube_comments.py: describe used approach - done
