### ISSUE TITLE
use smaller sample of the dataset

### ISSUE THREAD

**Issue by jakob-forstmann** [jakob-forstmann/sentiment-analysis-of-youtube-comments#4]
Since  we didn´t find a solution to optimize  the code reading the entire dataset we will use a smaller sample of the dataset. 
This will hopefully resolve #1 .
For the sampling i will try to use relevance sampling.

**Comment by hirschjn** [comment]
We can choose comments randomly at the beginning, when we load the comments from disk.
Because we will choose still very many comments, it is unlikely that the distribution of the selected ones will vary much from those the original (huge) data set.

**Comment by jakob-forstmann** [comment]
We prefer the other method since  very unlikely that the distribution will vary but it will most likely but faster than the 
current code for relevance sampling that will replicate the original distribution of the huge dataset.

**Comment by jakob-forstmann** [comment]
resolved by pull request #8
